export const styles = {
  container: {
    height: '100vh',
    background: 'linear-gradient(135deg, #4a90e2, #145ea8)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  loginBox: {
    backgroundColor: 'white',
    padding: 40,
    borderRadius: 12,
    boxShadow: '0 8px 30px rgba(0,0,0,0.12)',
    width: 360,
    display: 'flex',
    flexDirection: 'column',
  },
  input: {
    marginBottom: 15,
    padding: '12px 15px',
    borderRadius: 8,
    border: '1px solid #ddd',
    fontSize: 16,
    outline: 'none',
    transition: 'border-color 0.3s',
  },
  button: {
    padding: 15,
    backgroundColor: '#4a90e2',
    color: 'white',
    fontWeight: 'bold',
    border: 'none',
    borderRadius: 10,
    cursor: 'pointer',
    fontSize: 16,
    transition: 'background-color 0.3s',
  },
  chatBox: {
    backgroundColor: 'white',
    width: '100%',
    maxWidth: 600,
    height: '80vh',
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 12,
    boxShadow: '0 8px 30px rgba(0,0,0,0.15)',
  },
  header: {
    padding: 20,
    backgroundColor: '#145ea8',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  messagesContainer: {
    flexGrow: 1,
    padding: 20,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    overflowY: 'auto',
    backgroundColor: '#f7f9fc',
  },
  message: {
    maxWidth: '70%',
    padding: '12px 18px',
    borderRadius: 15,
    fontSize: 16,
    lineHeight: 1.4,
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    wordBreak: 'break-word',
  },
  inputContainer: {
    display: 'flex',
    padding: 15,
    borderTop: '1px solid #ddd',
  },
  textarea: {
    flexGrow: 1,
    resize: 'none',
    padding: 12,
    borderRadius: 10,
    border: '1px solid #ddd',
    fontSize: 16,
    fontFamily: 'inherit',
    outline: 'none',
  },
  sendButton: {
    marginLeft: 15,
    padding: '12px 25px',
    backgroundColor: '#4a90e2',
    color: 'white',
    border: 'none',
    borderRadius: 10,
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: 16,
    transition: 'background-color 0.3s',
  },
};
